version: '3'

networks:
  rensa_test_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.1.0/24

services:
  validator_0:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair FtUhvsHCGA6KePPcBDxLiKcuLyhKAz4W1iU4hX2CWtUd --genesis genesis.json --blocks-history 30
    networks:
      rensa_test_net:
        ipv4_address: 172.29.1.2

  validator_1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair 6GDs9UNWHp9oB6vPf7uSBocbJTR6Z4TQao7zQGDWE4Vu --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair 3TTteibqWqxdzDGg2oAvwatEs7iwXuFg45nprsFFpHEZ --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair csTUBKjVWS4P1Lq5fXQJ1U6JX2dEMef8MFzyNG21ycF --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_4:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair 6SebepsFketmvHW5wHc4PGK41Nt9JGfojUN5PXybPSuo --genesis genesis.json --peer 172.29.1.2:44668 --rpc 8080 --blocks-history 2000
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:
    ports:
      - "8080:8080"

  validator_5:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair 2r7N3U1vEsXGjm29TCfFTzwSuXjq9xPDiiah5egbSZpC --genesis genesis.json --peer 172.29.1.2:44668 --rpc 8080 --blocks-history 2000
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:
    ports:
      - "8081:8080"

  validator_6:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair Daa4SKexWyfgh5rN5DJUQAfEEQ4piJzRkf72CsBQJEtr --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_7:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
      # Uncomment for attaching a memory profiler
      # - LD_PRELOAD=/home/libbytehound.so
    # command: bash -c "./rensa --keypair 6zUWXGnHLqZzKBEJERqrLiM4v3QLMDWJpDbjt9QtwJcg --genesis genesis.json --peer 172.29.1.2:44668 && ./bytehound server -i 0.0.0.0 memory-profiling_*.dat"
    command: ./rensa --keypair 6zUWXGnHLqZzKBEJERqrLiM4v3QLMDWJpDbjt9QtwJcg --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:
    # Uncomment for attaching a memory profiler
    # ports:
    #   - "9090:8080"

  validator_8:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair Fi6HBTsAPURV75GEY1fPKXwF24pTikU4qsFc4TgrwbeB --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_9:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair 5jtFt9g9qYgicGbVS846BeZAyUbe7X7rvAWw3pNn2mXj --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_10:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair 6y7wHcUD1j1AQymapHkKaQ6fEMEFakBXY9xhdxh2AiCN --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30 --dbsync 'mysql://rensa:rensapwd@rensa-t1.cluster-cziy1rqqj0jj.eu-central-1.rds.amazonaws.com/rensa_t1'
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:
  
  validator_11:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair Bc51y46xTKtpA7WSCX4EnGDhmCRqxwp59xUPEZJtNw4e --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_12:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair CoGUcA3tWjGXuYjpDR211qFiTd4vAsXyXm1sL1yEYjzi --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_13:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair EDqLRR1denHBhZCabkdazD3dBmjxLM5iNN5Nq3axEw9z --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_14:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair H7xfZqfFpAvQsWTcqcL7h9VJbRAqAGsP85NukeyP1QBV --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_15:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair 4ZLA2dHg4b1V5ZJMthBx8CDYGCRkubbFh6mvLJYPaCzM --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_16:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair DpYhazJ6QRLQVcX3XwmZ9RGY2QCNCocWegXVxpvTXSw3 --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_17:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair 6uZYQhcF8bTuzaRG3y1T38AGeGcV9Ukm1C7rLU3qAvFX --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_18:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair 4qLfXAPn2zjiJ2jWNxYrz62fuMZkozSbkjfe7G6t8kr1 --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

  validator_19:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_BACKTRACE=1
    command: ./rensa --keypair 3zHk7yZdN3d62irDYCLUCRqW5pQxsTd8krwDwJtDbEbY --genesis genesis.json --peer 172.29.1.2:44668 --blocks-history 30
    depends_on:
      validator_0:
        condition: service_started
    networks:
      rensa_test_net:

